name: crypsi-mysql-udf CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
      runs-on: ubuntu-20.04
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: wuriyanto/mysql-crypsi:latest
  test:
    name: Test
    needs: docker-build
    runs-on: ubuntu-20.04

    services:
      postgres:
        image:  wuriyanto/mysql-crypsi:latest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Test
      run: |
        mysql -h localhost -P 3306 --database=test -u root --password=12345678 < ./scripts/test.sql